---
name: orangec-setup
description: Setup OrangeC for CMake
branding:
  color: blue
  icon: terminal
inputs:
  cache:
    required: false
    description: If caching should be used
    default: true
  cmake:
    required: false
    description: "`cmake` for modules install"
    default: cmake
  cmake-module:
    required: false
    description: Check OrangeC patch, install, if not
    default: check
  key-prefix:
    required: false
    description: Add prefix to cache key (for refresh or identification)
  verbose:
    required: false
    description: >-
      Show version and location `occ`, `make`, `cmake` ... form PATH.
    default: false
  version:
    required: false
    description: A specific version to install. Defaults to last (unspecified).
outputs:
  CMAKE_COMMAND:
    description: The full path to the `cmake` executable
    value: ${{ steps.cmake-report.outputs.CMAKE_COMMAND }}
  CMAKE_ROOT:
    description: Modules install directory for `cmake`
    value: ${{ steps.cmake-report.outputs.CMAKE_ROOT }}
runs:
  using: composite
  steps:
    - name: Check Orange C version compatible with CMake
      if: ${{ 'no' != inputs.cmake-module && '' != inputs.version }}
      shell: pwsh
      run: |
        $ov = "${{ inputs.version }}" -replace "[^0-9.]*$"
        $ocmk = "6.73"
        if ([version]$ov -lt [version]$ocmk) {
          Write-Error ("Orange C ${{ inputs.version }}" + `
                       " incompatible with CMake`n" + `
                       "Use Orange C >= $ocmk or ``cmake-module: 'no'``")
          Exit 1
        }

    - name: Install CMake OrangeC patch
      if: ${{ 'no' != inputs.cmake-module }}
      shell: pwsh -File {0}
      run: |
        $om = "$env:GITHUB_ACTION_PATH\OrangeC"
        if ("always" -eq "${{ inputs.cmake-module }}") {
          &"${{ inputs.cmake }}" -P "$om\uninstall.cmake"
          &"${{ inputs.cmake }}" -P "$om\install.cmake"
        } else {
          &"${{ inputs.cmake }}" -P "$om\detect.cmake"
          if (0 -ne $LASTEXITCODE) {
            &"${{ inputs.cmake }}" -P "$om\install.cmake"
          }
        }
        &"${{ inputs.cmake }}" -P "$om\detect.cmake"
        if ($${{ fromJSON(inputs.verbose) }}) {
          "inputs.cmake-module: ${{ inputs.cmake-module }}"
          "---"
        }

    - name: OrangeC directory and key
      id: od
      shell: pwsh
      run: |
        $key = "${{ inputs.key-prefix }}_OrangeC_${{ inputs.version }}_0.4"
        if ($${{ startsWith(inputs.version, '6.0') }}) {
          $od = "C:\Program Files (x86)\Orange C 386"
        } else {
          $od = "C:\Program Files (x86)\OrangeC"
        }
        mkdir "$od"
        "od=$od`n" + `
        "key=$key" >> $env:GITHUB_OUTPUT

    - name: Restore cached OrangeC directory
      id: cache-od
      if: inputs.cache == 'true'
      uses: actions/cache/restore@v5
      with:
        key: ${{ steps.od.outputs.key }}
        path: ${{ steps.od.outputs.od }}

    - name: Install OrangeC
      if: steps.cache-od.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        choco install --yes --no-progress `
                orangec --version=${{ inputs.version }}

    - name: Save cached OrangeC directory
      if: ${{ inputs.cache == 'true' &&
        steps.cache-od.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.od.outputs.key }}
        path: ${{ steps.od.outputs.od }}

    - name: OrangeC environments variables
      shell: pwsh
      run: |
        # https://orangec.readthedocs.io/en/latest/Tools/#tools-setup

        "ORANGEC=${{ steps.od.outputs.od }}" >> $env:GITHUB_ENV
        "${{ steps.od.outputs.od }}\bin" >> $env:GITHUB_PATH

    - name: Show version
      if: ${{ fromJSON(inputs.verbose) }}
      shell: pwsh
      run: |
        "PATH=$env:PATH"
        "---"
        "ORANGEC=$env:ORANGEC"
        get-command occ
        occ --version
        foreach ($prg in 'ar', 'make', 'cmake', 'choco') {
          try {
            get-command $prg
            &$prg --version | Select-Object -First 1
          } catch {}
        }

    - id: cmake-report
      if: ${{ 'no' != inputs.cmake-module }}
      shell: pwsh
      run: |
        &"${{ inputs.cmake }}" -P "$env:GITHUB_ACTION_PATH\cmake_report.cmake" `
          >> $env:GITHUB_OUTPUT
