# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

# Functions apply_patch/rev_apply_patch/save

function (apply_patch in patch out ok)
  if (in MATCHES "${${patch}_detect}")
    message(SEND_ERROR "apply_patch: matched '${${patch}_detect}'")
    set(${ok} 0 PARENT_SCOPE)
    return ()
endif ()
  string(REGEX REPLACE "${${patch}_match}" "${${patch}_replace}"
         repl "${in}")
  if (NOT repl MATCHES "${${patch}_detect}")
    message(SEND_ERROR "apply_patch: don't replaced for '${${patch}_detect}'")
    message("repl=${repl}")
    set(${ok} 0 PARENT_SCOPE)
    return ()
  endif ()
  string(REGEX REPLACE "${${patch}_rev_match}" "${${patch}_rev_replace}"
         cmp "${repl}")
  if (NOT in STREQUAL cmp)
    message(SEND_ERROR "apply_patch: patch don't reversible '${${patch}_detect}'")
    message("in: -----\n${in}-----")
    message("cmp: =====\n${cmp}=====")
    set(${ok} 0 PARENT_SCOPE)
    return ()
  endif ()
  set(${out} "${repl}" PARENT_SCOPE)
  set(${ok} 1 PARENT_SCOPE)
endfunction ()

function (rev_apply_patch in patch out ok)
  if (NOT in MATCHES "${${patch}_detect}")
    message(SEND_ERROR "rev_apply_patch: don't matched '${${patch}_detect}'")
    set(${ok} 0 PARENT_SCOPE)
    return ()
  endif ()
  string(REGEX REPLACE "${${patch}_rev_match}" "${${patch}_rev_replace}"
         repl "${in}")
  if (repl MATCHES "${${patch}_detect}")
    message(SEND_ERROR "rev_apply_patch: don't replaced for '${${patch}_detect}'")
    message("repl=${repl}")
    set(${ok} 0 PARENT_SCOPE)
    return ()
  endif ()
  string(REGEX REPLACE "${${patch}_match}" "${${patch}_replace}"
         cmp "${repl}")
  if (NOT in STREQUAL cmp)
    message(SEND_ERROR "rev_apply_patch: patch don't reversible '${${patch}_detect}'")
    message("in: -----\n${in}-----")
    message("cmp: =====\n${cmp}=====")
    set(${ok} 0 PARENT_SCOPE)
    return ()
  endif ()
  set(${out} "${repl}" PARENT_SCOPE)
  set(${ok} 1 PARENT_SCOPE)
endfunction ()

function (save filename suffix content)
  file(RENAME "${filename}" "${filename}.${suffix}")
  file(WRITE "${filename}" "${content}")
endfunction ()
