# vim:set sw=4 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2026 Сергей Леонтьев (leo@sai.msu.ru)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
include(_patches_)

message("detect: CMAKE_ROOT=${CMAKE_ROOT}")
set(fail 0)
file(READ "${CMAKE_ROOT}/Modules/Compiler/OrangeC.cmake" m)
file(READ "${CMAKE_ROOT}/Modules/Compiler/OrangeC-C.cmake" m_c)
file(READ "${CMAKE_ROOT}/Modules/Compiler/OrangeC-CXX.cmake" m_cxx)
if (NOT m MATCHES "${OrangeC_1_detect}")
    set(fail 1)
    message(STATUS "Don't detect '${OrangeC_1_detect}'")
endif ()
if (NOT m MATCHES "${OrangeC_2_detect}")
    set(fail 1)
    message(STATUS "Don't detect '${OrangeC_2_detect}'")
endif ()
if (NOT m_c MATCHES "${OrangeC_C_detect}")
    set(fail 1)
    message(STATUS "Don't detect '${OrangeC_C_detect}'")
endif ()
if (NOT m_cxx MATCHES "${OrangeC_CXX_detect}")
    set(fail 1)
    message(STATUS "Don't detect '${OrangeC_CXX_detect}'")
endif ()
if (fail)
    cmake_language(EXIT 1)
endif ()
message("Ok, detect '${OrangeC_CXX_detect}', '${OrangeC_C_detect}',"
        " '${OrangeC_2_detect}' and '${OrangeC_1_detect}'")
cmake_language(EXIT 0)
