---
# vim:set sw=2 ts=8 et fileencoding=utf8:
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2025 Сергей Леонтьев (leo@sai.msu.ru)

name: CMake on multiple platforms

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        version: ["", 6.73.1]  # 6.0.42.1 (6.42.1) don't supported by CMake
        os: [windows-latest, windows-2022]
        c_compiler: [occ]
        cpp_compiler: [occ]
        build_type: [Release]
        generator: ["MSYS Makefiles"]
        platform: [win32]
        # cmake_add: [--debug-trycompile]
        exclude:
          - {version: 6.73.1, os: windows-latest}

    steps:
      - uses: actions/checkout@v6

      - name: Lint
        if: matrix.os == 'windows-latest'  # One test
        run: |
          python -m pip install yamllint
          python -m yamllint --list-file .
          python -m yamllint .

      - name: Test action (Setup Orange C for CMake)
        uses: ./
        with:
          version: ${{ matrix.version }}
          verbose: true

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -G "${{ matrix.generator }}"
          -S .
          ${{ matrix.cmake_add }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --output-on-failure --build-config ${{ matrix.build_type }}
          --test-dir build

      - name: Run Windows
        run: |
          cd build\tests
          ./hello
          ./hello++
          ./bsd_echo my args
